---
title: "Variable selection in individual patient data meta-analysis - stent dataset"
author: "Michael Seo"
date: "5 August 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE, tidy.opts=list(blank=FALSE, width.cutoff=60), warning = FALSE, message=FALSE, echo = FALSE)
```


```{r}
# load packages needed
library(readstata13)

library(lme4) #for fitting glmm
library(glmnet) #for lasso
library(glmmLasso) #for glmmLasso
library(rjags) # for bayesian models
library(dclone) # for parallel processing of JAGS code

library(MASS) # Used for data simulation
library(nlme) # for initial values for glmmLasso
```


```{r}
# Setting directory
setwd("C:/Users/ms19g661/Desktop")
#setwd("C:/Users/mike/Desktop")
#stent <- read.dta13("stent.dta")
stent <- read.dta13("1_year_stent_data_21092018.dta")

#load/save everything else from/to github
setwd("~/GitHub/phd/varselect/stent")
#setwd("C:/Users/mike/Desktop/Github/phd/varselect/stent")
```


```{r Stent_data_processing}
# "age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "gpi", "new_p2y12", "num_stent"
# gender=1 is men, gender=0 is female
# dropped gpi, new_p2y12
# dropped study 19: too big
study_inclusion <- c(3, 4, 5, 12, 13, 14, 15, 17)
data0 <- stent[stent$trial_name %in% study_inclusion,]

#rename study
for(i in 1:dim(data0)[1]){
  data0$trial_name[i] <- which(data0$trial_name[i] == study_inclusion)
}
data0$trial_name <- as.factor(data0$trial_name)

X <-  data0[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")]

#recode categorical variables
ii <- sapply(X, is.factor)
X[ii] <- lapply(X[ii], as.character)
X[X == "Yes"] <- 1
X[X == "Male"] <- 1
X[X == "No"] <- 0
X[X == "Female"] <- 0
X[ii] <- lapply(X[ii], as.numeric)

data_stent <- cbind(X, y = data0$a_death_5yr_yn, treat = ifelse(data0$rand == "BMS", 0, 1), studyid = data0$trial_name)
mydata <- na.omit(data_stent)

# scale all variables
mydata[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")] <- apply(mydata[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")], 2, scale)

X <- mydata[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")]

# Total data: 11433 -> complete cases X: 11106 

col_labels_stent <- c("age", "gender", "diabetes", "stable_cad", "multivessel", "ladtreated", "overlap", "m_dia_above_3", "num_stent")
col_labels_stent_all <- c("(Intercept)", col_labels_stent, paste0(col_labels_stent, ":treat"), "treat", paste0("as.factor(studyid)", 1:length(unique(mydata$studyid))))
col_labels_stent_glmm <- c("(Intercept)", col_labels_stent, paste0(col_labels_stent, "_treat"), "treat", paste0("as.factor(studyid)", 1:length(unique(mydata$studyid))))

expit <- function(x){
  exp(x)/(1+exp(x))
}
```

## glmm_null

```{r glmm_null_stent, cache = TRUE}
m1 <- glmer(y ~ studyid + treat + (-1 + treat|studyid), data = mydata, family = binomial)
summary(m1)
```

```{r}
coef(m1)$studyid[1,]
contr <- c(rep(0, 8), 1)
v0 <- vcov(m1)
se0 <- c(sqrt(contr %*% v0 %*% contr))
mean0 <- c(contr %*% t(coef(m1)$studyid[1,]))

exp(mean0 + qnorm(c(.025,0.5,.975))* as.vector(se0[[1]]))
```

## glmm_full

```{r glmm_full_stent, cache = TRUE}
m2 <- glmer(y ~ studyid + (age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent)*treat + (-1 + treat|studyid), data = mydata, family = binomial)
summary(m2)
```

```{r}
# 80 years: 0.9325098, female(gender = 0): -1.6474649, diabetes=1: 1.8095668, stable_cad=0: -0.7168387, multivessel=1: 1.0778950, ladtreated = 1: 1.0691515, overlap=1: 2.348039, m_dia_above_3=0: -5.3789130, num_stents = 5 (3.1705418)
contr <- c(rep(0, 8), rep(0, 9), 1, 0.9325098, -1.6474649, 1.8095668, -0.7168387, 1.0778950, 1.0691515, 2.348039, -5.3789130, 3.1705418)
v1 <- vcov(m2)
se1 <- c(sqrt(contr %*% v1 %*% contr))
mean1 <- c(contr %*% t(coef(m2)$studyid[1,]))

exp(mean1 + qnorm(c(.025,0.5,.975))* as.vector(se1[[1]]))

# 50 years: -1.522422, male(gender =1): 0.606939, diabetes=0: -0.5525687, stable_cad=1: 1.3948883, multivessel=0: -0.9276506, ladtreated=0: -0.9352369, overlap=0: -0.425849, m_dia_above_3=1: 0.1858944, num_stents = 1: -0.6300019
contr <- c(rep(0, 8), rep(0, 9), 1, -1.522422, 0.606939, -0.5525687, 1.3948883, -0.9276506, -0.9352369, -0.425849, 0.1858944, -0.6300019)
v2 <- vcov(m2)
se2 <- c(sqrt(contr %*% v2 %*% contr))
mean2 <- c(contr %*% t(coef(m2)$studyid[1,]))

exp(mean2 + qnorm(c(.025,0.5,.975))* as.vector(se2[[1]]))
```

## naive step

```{r naive_step_stent, cache = TRUE, results = "hide"}
m3 <- glm(y ~ studyid + (age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent)*treat, family = binomial(link = "logit"), data = mydata)
s1 <- step(m3, scope=list(lower = ~ studyid + treat), direction = "both")
```

```{r}
summary(s1)
```

```{r}
# ladtreated = 1: 1.0691515, num_stents = 5: 3.1705418
contr <- c(rep(0, 8), rep(0, 7), 1, 1.0691515, 3.1705418)
v1 <- vcov(s1)
se1 <- c(sqrt(contr %*% v1 %*% contr))
mean1 <- c(contr %*% coef(s1))

exp(mean1 + qnorm(c(.025,0.5,.975))* as.vector(se1[[1]]))

# ladtreated=0: -0.9352369, num_stents = 1: -0.6300019
contr <- c(rep(0, 8), rep(0, 7), 1, -0.9352369, -0.6300019)
v2 <- vcov(s1)
se2 <- c(sqrt(contr %*% v2 %*% contr))
mean2 <-  c(contr %*% coef(s1))

exp(mean2 + qnorm(c(.025,0.5,.975))* as.vector(se2[[1]]))
```


## naive lasso

```{r glmnet_stent, cache = TRUE}
data_glmnet <- model.matrix(y~ studyid + (age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent)*treat, data = mydata)
data_glmnet <- data_glmnet[,-1]
data_glmnet <- cbind(y = mydata$y, data_glmnet = data_glmnet)

p.fac.stent <- c(rep(0, 7), rep(1, 9), 0, rep(1,9)) #No shrinkage for treatment effect and baseline effect
cvfit = cv.glmnet(as.matrix(data_glmnet[,-1]), as.matrix(data_glmnet[,1]), penalty.factor = p.fac.stent, family = "binomial", type.measure = "deviance", standardize = FALSE)
coef(cvfit, s = "lambda.min")
```

```{r glmnet_stent_bootstrap, cache = TRUE}
#bootstrapping LASSO function
bootstrap_function_LASSO  <- function(model_data, ndraws, p.fac) {
  
  coeff_mtx <- matrix(0, nrow = ndraws, ncol = length(colnames(model_data)))
  colnames(coeff_mtx) <- c("intercept", colnames(model_data)[-1])
  
  for (ii in 1:ndraws) {

    bootstrap_ids <- sample(seq(nrow(model_data)), nrow(model_data), replace = TRUE)
    bootstrap_data <- model_data[bootstrap_ids,]
    
    bootstrap_model <- cv.glmnet(as.matrix(bootstrap_data[,-1]), as.matrix(bootstrap_data[,1]), penalty.factor = p.fac, family = "binomial", type.measure = "deviance", standardize = FALSE)  
    aa <- coef(bootstrap_model, s = "lambda.min")
    coeff_mtx[ii,] <- aa[,1]
  }
  
  se <- apply(coeff_mtx, 2, sd, na.rm = TRUE)
  return(se)
}
bootstrap_function_LASSO(data_glmnet, 50, p.fac.stent)
```


```{r}
# aa[aa[,1] != 0,1]
# maybe needs fixing 
# ladtreated = 1: 1.0691515, num_stents = 5 (3.1705418)
mean1 <- c(1,  1.0691515, 3.1705418) %*% c(-0.096078318, -0.033438580, -0.004171182)
exp(mean1)

# ladtreated=0: -0.9352369, num_stents = 1: -0.6300019
mean2 <- c(1,  -0.9352369, -0.6300019) %*% c(-0.096078318, -0.033438580, -0.004171182)
exp(mean2)
```


## glmmLasso

```{r}
#function to cross validate glmmLasso
cv.glmmLasso <- function(data_glmmLasso, form.fixed = NULL, form.rnd = NULL, lambda = NULL, family = NULL, q_start = NULL, start = NULL){
  
  N <-dim(data_glmmLasso)[1]
  ind<-sample(N,N)
  
  kk <- 5 # 5 fold cross-validation
  nk <- floor(N/kk)
  
  Devianz_ma<-matrix(Inf,ncol=kk,nrow=length(lambda))
  
  for(j in 1:length(lambda)){
    print(paste("Iteration ", j,sep=""))
    
    for (i in 1:kk)
    {
      if (i < kk){
        indi <- ind[(i-1)*nk+(1:nk)]
      } else{
        indi <- ind[((i-1)*nk+1):N]
      }
    
      data_glmmLasso_train <- data_glmmLasso[-indi,]
      data_glmmLasso_test <- data_glmmLasso[indi,]

      glm2 <- try(glmmLasso(form.fixed, rnd = form.rnd,  
                            family = family, 
                            lambda = lambda[j],
                            data = data_glmmLasso_train,
                            control = list(index = c(NA, 1:((dim(data_glmmLasso)[2] - 3)), NA),
                                           center = FALSE, standardize = FALSE,
                                           q_start = q_start, start = start))
                  ,silent=TRUE) 
      if(class(glm2)!="try-error")
      {  
        y.hat<-predict(glm2,data_glmmLasso_test)    
        Devianz_ma[j,i]<-sum(family$dev.resids(data_glmmLasso_test$y,y.hat,wt=rep(1,length(y.hat))))
      }
    }
  }
  Devianz_vec<-apply(Devianz_ma,1,sum)
  opt2<-which.min(Devianz_vec)
  #print(Devianz_vec)
  #print(paste0("optimal lambda value is ", lambda[opt2]))
  lambda.min <- lambda[opt2]
  
  glm2 <- try(glmmLasso(form.fixed, rnd = form.rnd,  
                        family = family, 
                        lambda = lambda.min,
                        data = data_glmmLasso,
                        control = list(index = c(NA, 1:((dim(data_glmmLasso)[2] - 3)), NA),
                                       center = FALSE, standardize = FALSE,
                                       q_start = q_start, start = start))
              ,silent=TRUE)
  list(glm2 = glm2, lambda.min = lambda.min)
}
```


```{r glmmLasso_stent, cache = TRUE}
data_glmmLasso <- model.matrix(y~ -1 + (age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3  + num_stent)*treat, data = mydata)
data_glmmLasso <- cbind(y = mydata$y, data_glmmLasso = data_glmmLasso, studyid = mydata$studyid)

colnames(data_glmmLasso) <- gsub(":", "_", colnames(data_glmmLasso))  
data_glmmLasso <- as.data.frame(data_glmmLasso)
data_glmmLasso$studyid <- as.factor(data_glmmLasso$studyid)

form.fixed <- as.formula(y ~ as.factor(studyid) + age +  gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent + age_treat +  gender_treat + diabetes_treat + stable_cad_treat + multivessel_treat + ladtreated_treat + overlap_treat + m_dia_above_3_treat + num_stent_treat + treat)
form.rnd <- list(studyid =~ -1 + treat)

pql_formula <- as.formula("y ~ studyid + (age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent)*treat")
PQL <-glmmPQL(pql_formula, random = ~ -1 + treat|studyid, family=binomial, data=mydata)
q_start <- as.numeric(VarCorr(PQL)[1,1])
start <- as.numeric(c(PQL$coef$fixed[-which(names(PQL$coef$fixed) == "treat")], PQL$coef$fixed[which(names(PQL$coef$fixed) == "treat")], t(PQL$coef$random$studyid)))

cv.fit <- cv.glmmLasso(data_glmmLasso, form.fixed = form.fixed, form.rnd = form.rnd, lambda = seq(200, 0,
  by = -5), family = binomial(link = "logit"), q_start = q_start, start = start)
summary(cv.fit[[1]])
cv.fit[[2]]
```

```{r}
# 80 years: 0.9325098, female(gender = 0): -1.6474649, diabetes=1: 1.8095668, stable_cad=0: -0.7168387, multivessel=1: 1.0778950, ladtreated = 1: 1.0691515, overlap=1: 2.348039, m_dia_above_3=0: -5.3789130, num_stents = 5 (3.1705418)
contr <- c(0, rep(0, 9), c(0.9325098, -1.6474649, 1.8095668, -0.7168387, 1.0778950, 1.0691515, 2.348039, -5.3789130, 3.1705418), rep(0, 7), 1)

mean1 <- contr %*% cv.fit$glm2$coefficients
exp(mean1)

# 50 years: -1.522422, male(gender =1): 0.606939, diabetes=0: -0.5525687, stable_cad=1: 1.3948883, multivessel=0: -0.9276506, ladtreated=0: -0.9352369, overlap=0: -0.425849, m_dia_above_3=1: 0.1858944, num_stents = 1: -0.6300019
contr <- c(0, rep(0, 9), c(-1.522422, 0.606939, -0.5525687, 1.3948883, -0.9276506, -0.9352369, -0.425849, 0.1858944, -0.6300019), rep(0, 7), 1)

mean2 <- contr %*% cv.fit$glm2$coefficients
exp(mean2)
```


```{r}
# setup for parallel computing
n.cores <- 2
cl <- makePSOCKcluster(n.cores)
tmp <- clusterEvalQ(cl, library(dclone))

data_jags_stent <- with(mydata, {
        list(Nstudies = length(unique(studyid)),
        Ncovariate = 9,
        X = X,
        Np = dim(X)[1],
        studyid = studyid,
        treat = treat + 1,
        y = y
        )})
```


## Bayes Lasso

```{r bayesianLASSO_stent, cache = TRUE}
model_bayesLASSO <- jags.parfit(cl = cl, data = data_jags_stent, params = c("alpha","beta", "g", "d", "sdDelta", "lambda"), model = "IPD-MA-bayesLASSO-binomial.txt", n.chains = 2, n.adapt = 100, n.update = 1000, n.iter = 10000)
summary(model_bayesLASSO)
```

```{r, eval = FALSE}
plot(model_bayesLASSO[,"sdDelta"])
plot(model_bayesLASSO[,"d[2]"])
plot(model_bayesLASSO[,"lambda"])
```

```{r}
gelman.diag(model_bayesLASSO, multivariate = FALSE)
```

```{r}
# 80 years: 0.9325098, female(gender = 0): -1.6474649, diabetes=1: 1.8095668, stable_cad=0: -0.7168387, multivessel=1: 1.0778950, ladtreated = 1: 1.0691515, overlap=1: 2.348039, m_dia_above_3=0: -5.3789130, num_stents = 5: 3.1705418
mat1 <- do.call(rbind, model_bayesLASSO[,c("d[2]", "g[1]", "g[2]", "g[3]", "g[4]", "g[5]", "g[6]", "g[7]", "g[8]", "g[9]")])
sum1 <- mat1 %*% c(1, 0.9325098, -1.6474649, 1.8095668, -0.7168387, 1.0778950, 1.0691515, 2.348039, -5.3789130, 3.1705418)

mean1 <- mean(sum1)
se1 <- sd(sum1)
exp(mean1 + qnorm(c(.025,0.5,.975))* se1)

# 50 years: -1.522422, male(gender =1): 0.606939, diabetes=0: -0.5525687, stable_cad=1: 1.3948883, multivessel=0: -0.9276506, ladtreated=0: -0.9352369, overlap=0: -0.425849, m_dia_above_3=1: 0.1858944, num_stents = 1: -0.6300019
sum2 <- mat1 %*% c(1, -1.522422, 0.606939, -0.5525687, 1.3948883, -0.9276506, -0.9352369, -0.425849, 0.1858944, -0.6300019)

mean2 <- mean(sum2)
se2 <- sd(sum2)
exp(mean2 + qnorm(c(.025,0.5,.975))* se2)
```


## SSVS

```{r SSVS_stent, cache = TRUE}
model_SSVS <- jags.parfit(cl = cl, data = data_jags_stent, params = c("alpha", "beta", "g", "d", "sdDelta", "Ind", "Ind2", "eta"), model = "IPD-MA-SSVS-binomial.txt", n.chains = 3, n.adapt = 100, n.update = 1000, n.iter = 10000)
summary(model_SSVS)
```

```{r}
# 80 years: 0.9325098, female(gender = 0): -1.6474649, diabetes=1: 1.8095668, stable_cad=0: -0.7168387, multivessel=1: 1.0778950, ladtreated = 1: 1.0691515, overlap=1: 2.348039, m_dia_above_3=0: -5.3789130, num_stents = 5: 3.1705418
mat1 <- do.call(rbind, model_SSVS[,c("d[2]", "g[1]", "g[2]", "g[3]", "g[4]", "g[5]", "g[6]", "g[7]", "g[8]", "g[9]")])
sum1 <- mat1 %*% c(1, 0.9325098, -1.6474649, 1.8095668, -0.7168387, 1.0778950, 1.0691515, 2.348039, -5.3789130, 3.1705418)

mean1 <- mean(sum1)
se1 <- sd(sum1)
exp(mean1 + qnorm(c(.025,0.5,.975))* se1)

# 50 years: -1.522422, male(gender =1): 0.606939, diabetes=0: -0.5525687, stable_cad=1: 1.3948883, multivessel=0: -0.9276506, ladtreated=0: -0.9352369, overlap=0: -0.425849, m_dia_above_3=1: 0.1858944, num_stents = 1: -0.6300019
sum2 <- mat1 %*% c(1, -1.522422, 0.606939, -0.5525687, 1.3948883, -0.9276506, -0.9352369, -0.425849, 0.1858944, -0.6300019)

mean2 <- mean(sum2)
se2 <- sd(sum2)
exp(mean2 + qnorm(c(.025,0.5,.975))* se2)
```

```{r}
gelman.diag(model_SSVS, multivariate = FALSE)
```