---
title: "Variable selection in individual patient data meta-analysis - stent dataset"
author: "Michael Seo"
date: "5 August 2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE, tidy.opts=list(blank=FALSE, width.cutoff=60), warning = FALSE, message=FALSE, echo = FALSE)
```


```{r}
# load packages needed
library(readstata13)

library(lme4) #for fitting glmm
library(glmnet) #for lasso
library(R2jags)# for Bayesian models

library(MASS) # Used for data simulation
```


```{r}
# Setting directory
setwd("C:/Users/ms19g661/Desktop")
#setwd("C:/Users/mike/Desktop")
#stent <- read.dta13("stent.dta")
stent <- read.dta13("1_year_stent_data_21092018.dta")

#load/save everything else from/to github
setwd("~/GitHub/phd/varselect")
#setwd("C:/Users/mike/Desktop/Github/phd/varselect")
```


```{r}
# "age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "gpi", "new_p2y12", "num_stent"
# gender=1 is men, gender=0 is female
# dropped gpi, new_p2y12
# dropped study 19: too big
study_inclusion <- c(3, 4, 5, 12, 13, 14, 15, 17)
data0 <- stent[stent$trial_name %in% study_inclusion,]

#rename study
for(i in 1:dim(data0)[1]){
  data0$trial_name[i] <- which(data0$trial_name[i] == study_inclusion)
}
data0$trial_name <- as.factor(data0$trial_name)

X <-  data0[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")]

#recode categorical variables
ii <- sapply(X, is.factor)
X[ii] <- lapply(X[ii], as.character)
X[X == "Yes"] <- 1
X[X == "Male"] <- 1
X[X == "No"] <- 0
X[X == "Female"] <- 0
X[ii] <- lapply(X[ii], as.numeric)

data_stent <- cbind(X, y = data0$a_death_5yr_yn, treat = ifelse(data0$rand == "BMS", 0, 1), studyid = data0$trial_name)
mydata <- na.omit(data_stent)

# scale all variables
scale_mean <- apply(mydata[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")], 2, mean)

scale_sd <- apply(mydata[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")], 2, sd)

mydata[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")] <- apply(mydata[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")], 2, scale)

X <- mydata[,c("age", "gender", "diabetes", "stable_cad", "multivessel","ladtreated", "overlap", "m_dia_above_3", "num_stent")]

# Total data: 11433 -> complete cases X: 11106 

expit <- function(x){
  exp(x)/(1+exp(x))
}

### two patient subgroups
# 80 years: 0.9325098, female(gender = 0): -1.6474649, diabetes=1: 1.8095668, stable_cad=0: -0.7168387, multivessel=1: 1.0778950, ladtreated = 1: 1.0691515, overlap=1: 2.348039, m_dia_above_3=0: -5.3789130, num_stents = 5 (3.1705418)
group1 <- (c(80, 0, 1, 0, 1, 1, 1, 0, 5) - scale_mean) / scale_sd

# 50 years: -1.522422, male(gender =1): 0.606939, diabetes=0: -0.5525687, stable_cad=1: 1.3948883, multivessel=0: -0.9276506, ladtreated=0: -0.9352369, overlap=0: -0.425849, m_dia_above_3=1: 0.1858944, num_stents = 1: -0.6300019
group2 <- (c(50, 1, 0, 1, 0, 0, 0, 1, 1) - scale_mean) / scale_sd
```

## glmm_full

```{r glmm_full_stent, cache = TRUE}
m2 <- glmer(y ~ studyid + (age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent)*treat + (-1 + treat|studyid), data = mydata, family = binomial)
summary(m2)
```

```{r}
# group 1
contr <- c(rep(0, 8), rep(0, 9), 1, group1)
v1 <- vcov(m2)
se1 <- c(sqrt(contr %*% v1 %*% contr))
mean1 <- c(contr %*% t(coef(m2)$studyid[1,]))

exp(mean1 + qnorm(c(.025,0.5,.975))* as.vector(se1[[1]]))

# group 2
contr <- c(rep(0, 8), rep(0, 9), 1, group2)
v2 <- vcov(m2)
se2 <- c(sqrt(contr %*% v2 %*% contr))
mean2 <- c(contr %*% t(coef(m2)$studyid[1,]))

exp(mean2 + qnorm(c(.025,0.5,.975))* as.vector(se2[[1]]))
```

## naive step

```{r naive_step_stent, cache = TRUE, results = "hide"}
m3 <- glm(y ~ studyid + (age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent)*treat, family = binomial(link = "logit"), data = mydata)
s1 <- step(m3, scope=list(lower = ~ studyid + age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent + treat), direction = "both")
```

```{r}
summary(s1)
```

```{r}
# ladtreated = 1: 1.0691515, num_stents = 5: 3.1705418, 
contr <- c(rep(0, 8), rep(0, 9), 1, 1.0691515, 3.1705418)
v1 <- vcov(s1)
se1 <- c(sqrt(contr %*% v1 %*% contr))
mean1 <- c(contr %*% coef(s1))

exp(mean1 + qnorm(c(.025,0.5,.975))* as.vector(se1[[1]]))

# ladtreated=0: -0.9352369, num_stents = 1: -0.6300019
contr <- c(rep(0, 8), rep(0, 9), 1, -0.9352369, -0.6300019)
v2 <- vcov(s1)
se2 <- c(sqrt(contr %*% v2 %*% contr))
mean2 <-  c(contr %*% coef(s1))

exp(mean2 + qnorm(c(.025,0.5,.975))* as.vector(se2[[1]]))
```


## LASSO

```{r glmnet_stent, cache = TRUE}
set.seed(1)
data_glmnet <- model.matrix(y~ studyid + (age + gender + diabetes + stable_cad + multivessel + ladtreated + overlap + m_dia_above_3 + num_stent)*treat, data = mydata)
data_glmnet <- data_glmnet[,-1]
data_glmnet <- cbind(y = mydata$y, data_glmnet = data_glmnet)

p.fac.stent <- c(rep(0, 7), rep(0, 9), 0, rep(1,9)) #No shrinkage for treatment effect and baseline effect
cvfit = cv.glmnet(as.matrix(data_glmnet[,-1]), as.matrix(data_glmnet[,1]), penalty.factor = p.fac.stent, family = "binomial", type.measure = "deviance", standardize = FALSE)
coef(cvfit, s = "lambda.min")
```

```{r}
contr <- c(rep(0, 8), rep(0, 9), 1, group1)
exp(contr %*% coef(cvfit, s = "lambda.min"))

contr <- c(rep(0, 8), rep(0, 9), 1, group2)
exp(contr %*% coef(cvfit, s = "lambda.min"))
```



```{r}
bootstrap_function  <- function(model_data, ndraws, p.fac, family, alpha = 1, col_labels, lambdas = NULL) {
  
  coeff_mtx <- matrix(0, nrow = ndraws, ncol = length(col_labels))
  
  for (ii in 1:ndraws) {

    bootstrap_ids <- sample(seq(nrow(model_data)), nrow(model_data), replace = TRUE)
    bootstrap_data <- model_data[bootstrap_ids,]
    
    if(alpha == 0 & family == "binomial"){
      bootstrap_model <- cv.glmnet(as.matrix(bootstrap_data[,-1]), as.matrix(bootstrap_data[,1]), penalty.factor = p.fac, family = family, type.measure = "deviance", standardize = FALSE, alpha = alpha, lambda = lambdas)  
    }else {
      bootstrap_model <- cv.glmnet(as.matrix(bootstrap_data[,-1]), as.matrix(bootstrap_data[,1]), penalty.factor = p.fac, family = family, type.measure = "deviance", standardize = FALSE, alpha = alpha)  
    }
  
    aa <- coef(bootstrap_model, s = "lambda.min")
    coeff_mtx[ii,] <- sapply(col_labels, function(x) ifelse(x %in% rownames(aa)[aa[,1] != 0], aa[x,1], 0))  
  }
  se <- apply(coeff_mtx, 2, sd, na.rm = TRUE)
  return(se)
}
```


```{r}
bootstrap_function2  <- function(model_data, ndraws, p.fac, family, alpha = 1, contr_vec, lambdas = NULL) {
  
  predictions <- rep(NA, ndraws)
  
  for (ii in 1:ndraws) {

    bootstrap_ids <- sample(seq(nrow(model_data)), nrow(model_data), replace = TRUE)
    bootstrap_data <- model_data[bootstrap_ids,]
    
     if(alpha == 0 & family == "binomial"){
      bootstrap_model <- cv.glmnet(as.matrix(bootstrap_data[,-1]), as.matrix(bootstrap_data[,1]), penalty.factor = p.fac, family = family, type.measure = "deviance", standardize = FALSE, alpha = alpha, lambda = lambdas)  
    }else {
      bootstrap_model <- cv.glmnet(as.matrix(bootstrap_data[,-1]), as.matrix(bootstrap_data[,1]), penalty.factor = p.fac, family = family, type.measure = "deviance", standardize = FALSE, alpha = alpha)  
    }
    
    predictions[ii] <- exp(contr_vec %*% coef(bootstrap_model, s = "lambda.min"))

  }
  return(predictions)
}
```



```{r lasso_se, cache = TRUE}
col_labels <- c("age", "gender", "diabetes", "stable_cad", "multivessel", "ladtreated", "overlap", "m_dia_above_3", "num_stent", "age:treat", "gender:treat", "diabetes:treat", "stable_cad:treat", "multivessel:treat", "ladtreated:treat", "overlap:treat", "m_dia_above_3:treat", "num_stent:treat", "treat")
set.seed(1)
sd_values <- bootstrap_function(model_data = data_glmnet, ndraws = 50, p.fac = p.fac.stent, family = "binomial", alpha = 1, col_labels)
sd_values
```

```{r lasso_predictions, cache = TRUE}
set.seed(1)
contr <- c(rep(0, 8), rep(0, 9), 1, 0.9325098, -1.6474649, 1.8095668, -0.7168387, 1.0778950, 1.0691515, 2.348039, -5.3789130, 3.1705418)
predictions_group1 <- bootstrap_function2(model_data = data_glmnet, ndraws = 200, p.fac = p.fac.stent, family = "binomial", alpha = 1, contr_vec = contr)
quantile(predictions_group1, probs = c(0.025, 0.5, 0.975))

set.seed(1)
contr <- c(rep(0, 8), rep(0, 9), 1, -1.522422, 0.606939, -0.5525687, 1.3948883, -0.9276506, -0.9352369, -0.425849, 0.1858944, -0.6300019)
predictions_group2 <- bootstrap_function2(model_data = data_glmnet, ndraws = 200, p.fac = p.fac.stent, family = "binomial", alpha = 1, contr_vec = contr)
quantile(predictions_group2, probs = c(0.025, 0.5, 0.975))
```


## RIDGE

```{r ridge_stent, cache = TRUE}
set.seed(1)
lambdas <- 10^seq(3, -3, by = -.1) #manually specify lambda value to cross validate
cvfit = cv.glmnet(as.matrix(data_glmnet[,-1]), as.matrix(data_glmnet[,1]), penalty.factor = p.fac.stent, family = "binomial", type.measure = "deviance", standardize = FALSE, alpha = 0, lambda = lambdas)
coef(cvfit, s = "lambda.min")
```

```{r ridge_sd, cache = TRUE}
set.seed(1)
sd_values2 <- bootstrap_function(model_data = data_glmnet, ndraws = 50, p.fac = p.fac.stent, family = "binomial", alpha = 0, col_labels, lambda = lambdas)
sd_values2
```

```{r ridge_predictions, cache = TRUE}
set.seed(1)
contr <- c(rep(0, 8), rep(0, 9), 1, group1)
predictions_group1 <- bootstrap_function2(model_data = data_glmnet, ndraws = 200, p.fac = p.fac.stent, family = "binomial", alpha = 0, contr_vec = contr, lambda = lambdas)
quantile(predictions_group1, probs = c(0.025, 0.5, 0.975))

set.seed(1)
contr <- c(rep(0, 8), rep(0, 9), 1, group2)
predictions_group2 <- bootstrap_function2(model_data = data_glmnet, ndraws = 200, p.fac = p.fac.stent, family = "binomial", alpha = 0, contr_vec = contr, lambda = lambdas)
quantile(predictions_group2, probs = c(0.025, 0.5, 0.975))
```



## Bayesian

```{r}
data_jags_stent <- with(mydata, {
        list(Nstudies = length(unique(studyid)),
        Ncovariate = 9,
        X = X,
        Np = dim(X)[1],
        studyid = studyid,
        treat = treat + 1,
        y = y
        )})
```


## Bayes Lasso

```{r}
modelBayesLasso <- function(){

########## IPD-MA model
for (i in 1:Np){
	y[i] ~ dbern(p[i])  
	logit(p[i]) <- a[studyid[i]] + inprod(beta[], X[i,]) +
	 (1 - equals(treat[i],1)) * inprod(gamma[], X[i,]) + d[studyid[i],treat[i]] 
}

#####treatment effect
for(j in 1:Nstudies){
	d[j,1] <- 0
	d[j,2] ~ dnorm(delta[2], tau)
}

## prior distribution for heterogeneity of the treatment effect
tau <- pow(sd, -2)
sd ~ dnorm(0,1);T(0,)

## prior distribution for average treatment effect
delta[1] <- 0
delta[2] ~ dnorm(0, 0.001)

## prior distribution for baseline effect
for (j in 1:Nstudies){
	a[j] ~ dnorm(0, 0.001)	
}

## prior distribution for penalization parameter
#lambda ~ dgamma(0.001, 0.001)
lambda ~ dgamma(2, 0.1)

for(k in 1:Ncovariate){
	beta[k] ~ dnorm(0, 0.001)
}

for(k in 1:Ncovariate){
	gamma[k] ~ ddexp(0, lambda) 
}

}
```

```{r bayesianLASSO_stent, cache = TRUE, eval = FALSE}
model_bayesLASSO<- jags(data = data_jags_stent, inits = NULL,
                 parameters.to.save =  c("gamma", "delta", "beta", "sd"),
                 n.chains = 3, n.iter = 10000,
                 n.burnin = 1000,DIC=F,
                 model.file = modelBayesLasso)
```

```{r, eval = FALSE}
print(model_bayesLASSO)
model_bayesLASSO$BUGSoutput
```


```{r, eval =FALSE}
# 80 years: 0.9325098, female(gender = 0): -1.6474649, diabetes=1: 1.8095668, stable_cad=0: -0.7168387, multivessel=1: 1.0778950, ladtreated = 1: 1.0691515, overlap=1: 2.348039, m_dia_above_3=0: -5.3789130, num_stents = 5: 3.1705418
mat1 <- model_bayesLASSO$BUGSoutput$sims.matrix[,c("delta[2]", "gamma[1]", "gamma[2]", "gamma[3]", "gamma[4]", "gamma[5]", "gamma[6]", "gamma[7]", "gamma[8]", "gamma[9]")]
sum1 <- mat1 %*% c(1, 0.9325098, -1.6474649, 1.8095668, -0.7168387, 1.0778950, 1.0691515, 2.348039, -5.3789130, 3.1705418)

mean1 <- mean(sum1)
se1 <- sd(sum1)
exp(mean1 + qnorm(c(.025,0.5,.975))* se1)

# # 50 years: -1.522422, male(gender =1): 0.606939, diabetes=0: -0.5525687, stable_cad=1: 1.3948883, multivessel=0: -0.9276506, ladtreated=0: -0.9352369, overlap=0: -0.425849, m_dia_above_3=1: 0.1858944, num_stents = 1: -0.6300019
sum2 <- mat1 %*% c(1, -1.522422, 0.606939, -0.5525687, 1.3948883, -0.9276506, -0.9352369, -0.425849, 0.1858944, -0.6300019)

mean2 <- mean(sum2)
se2 <- sd(sum2)
exp(mean2 + qnorm(c(.025,0.5,.975))* se2)
```


## SSVS

```{r}
modelSSVS <- function(){

########## IPD-MA model
for (i in 1:Np){
	y[i] ~ dbern(p[i])
	logit(p[i]) <- a[studyid[i]] + inprod(beta[], X[i,]) +
	 (1 - equals(treat[i],1)) * inprod(gamma[], X[i,]) + d[studyid[i],treat[i]] 
}

#####treatment effect
for(j in 1:Nstudies){
	d[j,1] <- 0
	d[j,2] ~ dnorm(delta[2], tau)
}

## prior distribution for heterogeneity of the treatment effect
tau <- pow(sd, -2)
sd ~ dnorm(0,1);T(0,)

## prior distribution for average treatment effect
delta[1] <- 0
delta[2] ~ dnorm(0, 0.001)

## prior distribution for baseline effect
for (j in 1:Nstudies){
	a[j] ~ dnorm(0, 0.001)	
}

for(k in 1:Ncovariate){
	beta[k] ~ dnorm(0, 0.001)
}

for(k in 1:Ncovariate){
	IndA[k] ~ dcat(Pind[])
	Ind[k] <- IndA[k] - 1
	gamma[k] ~ dnorm(0, tauCov[IndA[k]])
}

zeta <- pow(eta, -2)
eta ~ dunif(0, 5)
tauCov[1] <- zeta
tauCov[2] <- zeta * 0.01  # g = 100

Pind[1] <- 0.5 #P(I_j=1)= 0.5
Pind[2] <- 0.5 

}

```


```{r SSVS_stent, cache = TRUE, eval = FALSE}
model_SSVS <- jags(data = data_jags_stent, inits = NULL,
                 parameters.to.save =  c("gamma", "delta", "beta", "sd", "Ind"),
                 n.chains = 3, n.iter = 10000,
                 n.burnin = 1000, DIC=F,
                 model.file = modelSSVS)
```

```{r, eval = FALSE}
print(model_SSVS)
model_SSVS$BUGSoutput
```


```{r, eval = FALSE}
# 80 years: 0.9325098, female(gender = 0): -1.6474649, diabetes=1: 1.8095668, stable_cad=0: -0.7168387, multivessel=1: 1.0778950, ladtreated = 1: 1.0691515, overlap=1: 2.348039, m_dia_above_3=0: -5.3789130, num_stents = 5: 3.1705418
mat1 <- model_SSVS$BUGSoutput$sims.matrix[,c("delta[2]", "gamma[1]", "gamma[2]", "gamma[3]", "gamma[4]", "gamma[5]", "gamma[6]", "gamma[7]", "gamma[8]", "gamma[9]")]
sum1 <- mat1 %*% c(1, 0.9325098, -1.6474649, 1.8095668, -0.7168387, 1.0778950, 1.0691515, 2.348039, -5.3789130, 3.1705418)

mean1 <- mean(sum1)
se1 <- sd(sum1)
exp(mean1 + qnorm(c(.025,0.5,.975))* se1)

# 50 years: -1.522422, male(gender =1): 0.606939, diabetes=0: -0.5525687, stable_cad=1: 1.3948883, multivessel=0: -0.9276506, ladtreated=0: -0.9352369, overlap=0: -0.425849, m_dia_above_3=1: 0.1858944, num_stents = 1: -0.6300019
sum2 <- mat1 %*% c(1, -1.522422, 0.606939, -0.5525687, 1.3948883, -0.9276506, -0.9352369, -0.425849, 0.1858944, -0.6300019)

mean2 <- mean(sum2)
se2 <- sd(sum2)
exp(mean2 + qnorm(c(.025,0.5,.975))* se2)
```

