---
title: "within and between trial variation addition"
author: "Michael Seo"
date: "5 Oktober 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/GitHub/phd/varselect")
#setwd("C:/Users/mike/Desktop/Github/phd/varselect")

library(MASS) # Used for data simulation

library(lme4) #for fitting glmm
library(glmnet) #for lasso


source("run.simulation.functions.modified2.R")
source("helpful.functions.R")

### parameters to change ###
col_labels <- c(paste0("X", 1:10, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:10, "_treat"), "treat")

correct_em <- c(0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
correct_em_values <- c(0, 0, 0, 0.3, 0.5, 0, 0, 0, 0, 0)

Nstudies <- 5
Ncovariate <- 10
continuous.cov <- c(1, 2, 4, 6, 7, 8)
pf <- c(1,2,3,4,5)
em <- c(4,5)
b1 <- c(0.1, 0.1, 0.5, 0.3, 0.5)
b2 <- c(0.3, 0.5)

glmm_oracle_formula <- as.formula("y ~ studyid + X1 + X2 + X3 + X4 + X5 + X4 * treat + X5 * treat + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + X6_treat + X7_treat + X8_treat + X9_treat + X10_treat + treat")

model.type = "gaussian"


data <-generate.simulation(Nstudies = Nstudies, Ncovariate = Ncovariate, continuous.cov = continuous.cov, pf = pf, em = em, b1 = b1, b2 = b2, model.type = model.type)

library(dplyr)
library(tibble)

newdata1 <-
  as.data.frame(data[,c(2:11, 23)] %>%
                  group_by(studyid) %>%
                  mutate_all(funs(Z = .- mean(.), Zbar = mean(.))))
newdata1 <- cbind(newdata1, treat = data$treat, y = data$y)
newdata2 <- model.matrix(y~ studyid + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + 
               (X1_Zbar + X2_Zbar + X3_Zbar + X4_Zbar + X5_Zbar + X6_Zbar + X7_Zbar + X8_Zbar + X9_Zbar + X10_Zbar):treat + 
               (X1_Z + X2_Z + X3_Z + X4_Z + X5_Z + X6_Z + X7_Z + X8_Z + X9_Z + X10_Z):treat + treat, data = newdata1)
newdata2 <- newdata2[,-1] 
newdata2 <- cbind(y = data$y, newdata2= newdata2)  

#penalize only within study variation 
p.fac <- c(rep(0, Nstudies - 1), rep(0, Ncovariate), 0, rep(0, Ncovariate), rep(1, Ncovariate))

family <- ifelse(model.type == "gaussian", "gaussian", "binomial")
cvfit <- cv.glmnet(as.matrix(newdata2[,-1]), as.matrix(newdata2[,1]), penalty.factor = p.fac, family = family, standardize = FALSE, type.measure = "deviance")  
aa <- coef(cvfit, s = "lambda.min")
aa

#penalize both within study variation and between study variation
p.fac <- c(rep(0, Nstudies - 1), rep(0, Ncovariate), 0, rep(1, Ncovariate), rep(1, Ncovariate))

cvfit <- cv.glmnet(as.matrix(newdata2[,-1]), as.matrix(newdata2[,1]), penalty.factor = p.fac, family = family, standardize = FALSE, type.measure = "deviance")  
aa <- coef(cvfit, s = "lambda.min")
aa

```