---
title: "Simulations"
author: "Michael Seo"
date: "16 August 2019"
output: word_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE, tidy.opts=list(blank=FALSE, width.cutoff=60), warning = FALSE, message=FALSE, echo = FALSE)
```


```{r}
# load packages needed
library(MASS) # Used for data simulation

library(lme4) #for fitting glmm
library(glmnet) #for lasso
library(glmmLasso) #for glmmLasso
library(dclone) # for parallel processing of JAGS code
library(knitr) # for tables
library(nlme) # for initial values for glmmLasso
```

```{r}
#load/save everything else from/to github
#setwd("~/GitHub/phd/varselect")
setwd("C:/Users/mike/Desktop/Github/phd/varselect")

source("run.simulation.functions.R")
source("helpful.functions.R")

# setup for parallel computing
n.cores <- 2
cl <- makePSOCKcluster(n.cores)
tmp <- clusterEvalQ(cl, library(dclone))

# number of simulation to run
niter <- 1000
```

## Simulation 1

```{r, simulation1}
### parameters to change ###
col_labels_glmm <- c(paste0("treat:", "X", 1:5), "treat")
col_labels <- c(paste0("X", 1:5, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:5, "_treat"), "treat")

correct_em <- c(0, 0, 1, 0, 0)
correct_em_values <- c(0, 0, 0.1, 0, 0)

Nstudies <- 5
Ncovariate <- 5
continuous.cov <- c(1, 3, 4)
pf <- c(1,2,3)
em <- 3
b1 <- c(0.1, 0.5, 0.1)
b2 <- 0.1

glmm_null_formula <- as.formula("y ~ studyid + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + treat")

model.type = "gaussian"
```

```{r simulation1a, cache = TRUE, result = "hide", include = FALSE}
simulation1.a <- run.simulation()
```

```{r simulation1b, cache = TRUE, result = "hide", include = FALSE}
simulation1.b <- run.simulation2()
```

```{r}
simulation1.a
simulation1.b
```

## Simulation 2

```{r, simulation2}
### parameters to change ###
col_labels <- c(paste0("X", 1:5, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:5, "_treat"), "treat")

correct_em <- c(0, 0, 1, 0, 0)
correct_em_values <- c(0, 0, 0.5, 0, 0)

Nstudies <- 5
Ncovariate <- 5
continuous.cov <- c(1, 3, 4)
pf <- c(1,2,3)
em <- 3
b1 <- c(0.1, 0.5, 0.1)
b2 <- 0.5

glmm_null_formula <- as.formula("y ~ studyid + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + treat")

model.type = "gaussian"
```

```{r simulation2a, cache = TRUE, result = "hide", include = FALSE}
simulation2.a <- run.simulation()
```

```{r simulation2b, cache = TRUE, result = "hide", include = FALSE}
simulation2.b <- run.simulation2()
```

```{r}
simulation2.a
simulation2.b
```

## Simulation 3

```{r, simulation3}
### parameters to change ###
col_labels <- c(paste0("X", 1:10, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:10, "_treat"), "treat")

correct_em <- c(0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
correct_em_values <- c(0, 0, 0, 0.1, 0.2, 0, 0, 0, 0, 0)

Nstudies <- 5
Ncovariate <- 10
continuous.cov <- c(1, 2, 4, 6, 7, 8)
pf <- c(1,2,3,4,5)
em <- c(4,5)
b1 <- c(0.1, 0.1, 0.5, 0.1, 0.5)
b2 <- c(0.1, 0.2)

glmm_null_formula <- as.formula("y ~ studyid + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + X6_treat + X7_treat + X8_treat + X9_treat + X10_treat + treat")

model.type = "gaussian"
```

```{r simulation3a, cache = TRUE, result = "hide", include = FALSE}
simulation3.a <- run.simulation()
```

```{r simulation3b, cache = TRUE, result = "hide", include = FALSE}
simulation3.b <- run.simulation2()
```

```{r}
simulation3.a
simulation3.b
```

## Simulation 4

```{r, simulation4}
### parameters to change ###
col_labels <- c(paste0("X", 1:10, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:10, "_treat"), "treat")

correct_em <- c(0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
correct_em_values <- c(0, 0, 0, 0.5, 1.0, 0, 0, 0, 0, 0)

Nstudies <- 5
Ncovariate <- 10
continuous.cov <- c(1, 2, 4, 6, 7, 8)
pf <- c(1,2,3,4,5)
em <- c(4,5)
b1 <- c(0.1, 0.1, 0.5, 0.1, 0.5)
b2 <- c(0.5, 1.0)

glmm_null_formula <- as.formula("y ~ studyid + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + X6_treat + X7_treat + X8_treat + X9_treat + X10_treat + treat")

model.type = "gaussian"
```

```{r simulation4a, cache = TRUE, result = "hide", include = FALSE}
simulation4.a <- run.simulation()
```

```{r simulation4b, cache = TRUE, result = "hide", include = FALSE}
simulation4.b <- run.simulation2()
```

```{r}
simulation4.a
simulation4.b
```


## Simulation 5

```{r, simulation5}
### parameters to change ###
col_labels_glmm <- c(paste0("treat:", "X", 1:5), "treat")
col_labels <- c(paste0("X", 1:5, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:5, "_treat"), "treat")

correct_em <- c(0, 0, 1, 0, 0)
correct_em_values <- c(0, 0, 0.1, 0, 0)

Nstudies <- 5
Ncovariate <- 5
continuous.cov <- c(1, 3, 4)
pf <- c(1,2,3)
em <- 3
b1 <- c(0.1, 0.5, 0.1)
b2 <- 0.1

glmm_null_formula <- as.formula("y ~ studyid + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + treat")

model.type = "binary"
```

```{r simulation5a, cache = TRUE, result = "hide", include = FALSE}
simulation5.a <- run.simulation()
```

```{r simulation5b, cache = TRUE, result = "hide", include = FALSE}
simulation5.b <- run.simulation2()
```

```{r}
simulation5.a
simulation5.b
```



## Simulation 6

```{r, simulation6}
### parameters to change ###
col_labels <- c(paste0("X", 1:5, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:5, "_treat"), "treat")

correct_em <- c(0, 0, 1, 0, 0)
correct_em_values <- c(0, 0, 0.5, 0, 0)

Nstudies <- 5
Ncovariate <- 5
continuous.cov <- c(1, 3, 4)
pf <- c(1,2,3)
em <- 3
b1 <- c(0.1, 0.5, 0.1)
b2 <- 0.5

glmm_null_formula <- as.formula("y ~ studyid + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + treat")

model.type = "binary"
```

```{r simulation6a, cache = TRUE, result = "hide", include = FALSE}
simulation6.a <- run.simulation()
```

```{r simulation6b, cache = TRUE, result = "hide", include = FALSE}
simulation6.b <- run.simulation2()
```

```{r}
simulation6.a
simulation6.b
```


## Simulation 7

```{r, simulation7}
### parameters to change ###
col_labels <- c(paste0("X", 1:10, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:10, "_treat"), "treat")

correct_em <- c(0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
correct_em_values <- c(0, 0, 0, 0.1, 0.2, 0, 0, 0, 0, 0)

Nstudies <- 5
Ncovariate <- 10
continuous.cov <- c(1, 2, 4, 6, 7, 8)
pf <- c(1,2,3,4,5)
em <- c(4,5)
b1 <- c(0.1, 0.1, 0.5, 0.1, 0.5)
b2 <- c(0.1, 0.2)

glmm_null_formula <- as.formula("y ~ studyid + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + X6_treat + X7_treat + X8_treat + X9_treat + X10_treat + treat")

model.type = "binary"
```

```{r simulation7a, cache = TRUE, result = "hide", include = FALSE, eval = FALSE}
simulation7.a <- run.simulation()
```

```{r simulation7b, cache = TRUE, result = "hide", include = FALSE, eval = FALSE}
simulation7.b <- run.simulation2()
```

```{r}
#simulation7.a
#simulation7.b
```


## Simulation 8

```{r, simulation8}
### parameters to change ###
col_labels <- c(paste0("X", 1:10, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:10, "_treat"), "treat")

correct_em <- c(0, 0, 0, 1, 1, 0, 0, 0, 0, 0)
correct_em_values <- c(0, 0, 0, 0.5, 1.0, 0, 0, 0, 0, 0)

Nstudies <- 5
Ncovariate <- 10
continuous.cov <- c(1, 2, 4, 6, 7, 8)
pf <- c(1,2,3,4,5)
em <- c(4,5)
b1 <- c(0.1, 0.1, 0.5, 0.1, 0.5)
b2 <- c(0.5, 1.0)

glmm_null_formula <- as.formula("y ~ studyid + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10)*treat")
glmmLasso_formula <- as.formula("y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat + X6_treat + X7_treat + X8_treat + X9_treat + X10_treat + treat")

model.type = "binary"
```

```{r simulation8a, cache = TRUE, result = "hide", include = FALSE, eval = FALSE}
simulation8.a <- run.simulation()
```

```{r simulation8b, cache = TRUE, result = "hide", include = FALSE, eval = FALSE}
simulation8.b <- run.simulation2()
```

```{r}
#simulation8.a
#simulation8.b
```
