---
title: "Simulation1"
author: "Michael Seo"
date: "15 August 2019"
output: word_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE, tidy.opts=list(blank=FALSE, width.cutoff=60), warning = FALSE, message=FALSE, echo = FALSE)
```


```{r}
# load packages needed
library(MASS) # Used for data simulation

library(lme4) #for fitting glmm
library(glmnet) #for lasso
library(glmmLasso) #for glmmLasso
library(dclone) # for parallel processing of JAGS code
library(knitr) # for tables
```

```{r}
# Setting directory
#setwd("C:/Users/ms19g661/Desktop")
setwd("C:/Users/mike/Desktop")

#load/save everything else from/to github
#setwd("~/GitHub/phd/varselect")
setwd("C:/Users/mike/Desktop/Github/phd/varselect")

source("helpful.functions.R")

# setup for parallel computing
n.cores <- 3
cl <- makePSOCKcluster(n.cores)
tmp <- clusterEvalQ(cl, library(dclone))
```

```{r}
niter <- 1000 #number of simulation to run

col_labels_glmm <- c(paste0("treat:", "X", 1:5), "treat")
col_labels <- c(paste0("X", 1:5, ":treat"), "treat")
col_labels_glmmLasso <- c(paste0("X", 1:5, "_treat"), "treat")

correct_em <- c(0, 0, 1, 0, 0)
correct_em_values <- c(0, 0, 0.1, 0, 0)




# col_labels <- c(paste0("X", 1:5), paste0("X", 1:5))
# col_labels <- c(paste0("X", 1:10), paste0("X", 1:10, ":treat"), "treat") # first simulation data
# col_labels2 <- c(paste0("X", 1:20), paste0("X", 1:20, ":treat"), "treat") # second
# col_labels_glmmLasso <- c(paste0("X", 1:10), paste0("X", 1:10, "_treat"), "treat")
# col_labels_glmmLasso2 <- c(paste0("X", 1:20), paste0("X", 1:20, "_treat"), "treat")
# 
# correct_em <- c(rep(0, 3), rep(1, 2), rep(0, 5))
# correct_em2 <- c(rep(0, 6), rep(1, 4), rep(0, 10))
# correct_em_values <- c(0, 0, 0, 0.2, 0.3, 0, 0, 0, 0, 0)
# correct_em_values2 <- c(rep(0, 6), 0.2, 0.3, -0.1, -0.2, rep(0, 10))
# generate.simulation(Nstudies = 5, Ncovariate = 10, continuous.cov = c(1,2,4,6,7,8), pf = c(1,2,3,4,5), em = c(4,5), b1 = c(0.1, 0.1, 0.5, 0.1, 0.5))
```


## glmm_null

```{r glmm_null, cache = TRUE, results = "hide", include = FALSE}
glmm_null_store_mse <- matrix(NA, nrow = niter, ncol = 3)
glmm_null_store_sd <- matrix(NA, nrow = niter, ncol = 2)

for(i in seq(niter)){
  
  set.seed(i)
  data <-generate.simulation(Nstudies = 5, Ncovariate = 5, continuous.cov = c(1, 3, 4), pf = c(1,2,3), em = 3, b1 = c(0.1, 0.5, 0.1), b2 = 0.1)
  m1 <- lmer(y ~ studyid + treat + (-1 + treat|studyid), data = data)
  
  mean_values <- sapply(col_labels_glmm, function(x) ifelse(x %in% names(fixef(m1)), summary(m1)$coef[x,"Estimate"], 0))
  sd_values <- sapply(col_labels_glmm, function(x) ifelse(x %in% names(fixef(m1)), summary(m1)$coef[x,"Std. Error"], 0))
  
  glmm_null_store_mse[i,] <- find_performance(mean_values, correct_em_values, correct_em)
  glmm_null_store_sd[i,] <- find_performance2(sd_values, correct_em)
}
glmm_null_store_mse_mean <- apply(glmm_null_store_mse, 2, mean)
glmm_null_store_sd_mean <- apply(glmm_null_store_sd, 2, mean)
```

## glmm_full

```{r glmm_full, cache = TRUE, results = "hide", include = FALSE}
glmm_full_store_mse <- matrix(NA, nrow = niter, ncol = 3)
glmm_full_store_sd <- matrix(NA, nrow = niter, ncol = 2)

for(i in seq(niter)){
  
  set.seed(i)
  data <-generate.simulation(Nstudies = 5, Ncovariate = 5, continuous.cov = c(1, 3, 4), pf = c(1,2,3), em = 3, b1 = c(0.1, 0.5, 0.1), b2 = 0.1)
  m1 <- lmer(y ~ studyid + treat + (X1 + X2 + X3 + X4 + X5)*treat + (-1 + treat|studyid), data = data)
  
  mean_values <- sapply(col_labels_glmm, function(x) ifelse(x %in% names(fixef(m1)), summary(m1)$coef[x,"Estimate"], 0))
  sd_values <- sapply(col_labels_glmm, function(x) ifelse(x %in% names(fixef(m1)), summary(m1)$coef[x,"Std. Error"], 0))
  
  glmm_full_store_mse[i,] <- find_performance(mean_values, correct_em_values, correct_em)
  glmm_full_store_sd[i,] <- find_performance2(sd_values, correct_em)
}
glmm_full_store_mse_mean <- apply(glmm_full_store_mse, 2, mean)
glmm_full_store_sd_mean <- apply(glmm_full_store_sd, 2, mean)
```


## naive step

```{r step_model, cache = TRUE, results = "hide"}
step_store_mse <- matrix(NA, nrow = niter, ncol = 3)
step_store_sd <- matrix(NA, nrow = niter, ncol = 2)

for(i in seq(niter)){

  set.seed(i)
  data <-generate.simulation(Nstudies = 5, Ncovariate = 5, continuous.cov = c(1, 3, 4), pf = c(1,2,3), em = 3, b1 = c(0.1, 0.5, 0.1), b2 = 0.1)

  m1 <- lm(y ~ (X1 + X2 + X3 + X4 + X5)*treat, data = data)
  s1 <- step(m1, scope=list(lower=~treat))
 
  mean_values <- sapply(col_labels, function(x) ifelse(x %in% variable.names(s1), summary(s1)$coef[x,"Estimate"], 0))
  sd_values <- sapply(col_labels, function(x) ifelse(x %in% variable.names(s1), summary(s1)$coef[x,"Std. Error"], 0))
  
  step_store_mse[i,] <- find_performance(mean_values, correct_em_values, correct_em)
  step_store_sd[i,] <- find_performance2(sd_values, correct_em)
}
step_store_mse_mean <- apply(step_store_mse, 2, mean)
step_store_sd_mean <- apply(step_store_sd, 2, mean)
```


## glmnet

```{r glmnet, cache = TRUE}
glmnet_store_mse <- matrix(NA, nrow = niter, ncol = 3)

for(i in seq(niter)){

  set.seed(i)
  data <-generate.simulation(Nstudies = 5, Ncovariate = 5, continuous.cov = c(1, 3, 4), pf = c(1,2,3), em = 3, b1 = c(0.1, 0.5, 0.1), b2 = 0.1)
  data$studyid <- NULL

  p.fac <- rep(1, length(col_labels)*2 - 1)
  p.fac[length(col_labels)] <- 0

  cvfit <- cv.glmnet(as.matrix(data[,-1]), as.matrix(data[1]), penalty.factor = p.fac)
  aa <- coef(cvfit, s = "lambda.min")

  mean_values <-  sapply(col_labels, function(x) ifelse(x %in% rownames(aa)[aa[,1] != 0], aa[x,1], 0))
  glmnet_store_mse[i,] <- find_performance(mean_values, correct_em_values, correct_em)
}
glmnet_store_mse_mean <- apply(glmnet_store_mse, 2, mean)
```

## glmmLasso

```{r glmmLasso, cache = TRUE, result = "hide", include = FALSE}
glmmLasso_store_mse <- matrix(NA, nrow = niter, ncol = 3)

for(i in seq(niter)){
  
  set.seed(i)  
  data <-generate.simulation(Nstudies = 5, Ncovariate = 5, continuous.cov = c(1, 3, 4), pf = c(1,2,3), em = 3, b1 = c(0.1, 0.5, 0.1), b2 = 0.1)
  colnames(data) <- gsub(":", "_", colnames(data))  

  form.fixed <- as.formula(y ~ as.factor(studyid) + X1 + X2 + X3 + X4 + X5 + X1_treat + X2_treat + X3_treat + X4_treat + X5_treat +  treat)
  form.rnd <- list(studyid =~ -1 + treat)
  
  cv.fit <- cv.glmmLasso(data, form.fixed = form.fixed, form.rnd = form.rnd, lambda = seq(100, 0, by = -5), family = gaussian(link="identity"))
  
  aa <- summary(cv.fit)$coefficients
  aa <- rownames(aa[aa[,"Estimate"] != 0,])

  mean_values <- sapply(col_labels_glmmLasso, function(x) ifelse(x %in% aa, summary(cv.fit)$coefficients[x,"Estimate"], 0))
  glmmLasso_store_mse[i,] <- find_performance(mean_values, correct_em_values, correct_em)
}
glmmLasso_store_mse_mean <- apply(glmmLasso_store_mse, 2, mean)
```


## Bayes Lasso

```{r bayesLASSO, cache = TRUE, results = "hide"}
bayesLASSO_store_mse <- matrix(NA, nrow = niter, ncol = 3)
bayesLASSO_store_sd <- matrix(NA, nrow = niter, ncol = 2)

for(i in seq(niter)){

  set.seed(i)
  data <-generate.simulation(Nstudies = 5, Ncovariate = 5, continuous.cov = c(1, 3, 4), pf = c(1,2,3), em = 3, b1 = c(0.1, 0.5, 0.1), b2 = 0.1)
  data_jags <- with(data,{
                  list(Nstudies = length(unique(studyid)),
                  X = cbind(X1, X2, X3, X4, X5),
                  Np = length(X1),
                  Ncovariate = (dim(data)[2] - 3)/2,
                  studyid = studyid,
                  treat = treat + 1,
                  y = y)
  })
  
  samples <- jags.parfit(cl = cl, data = data_jags, params = c("g", "d"), model = "IPD-MA-bayesLASSO.txt", n.chains = 3, n.adapt = 100, n.update = 100, n.iter = 2000)

  a <- summary(samples)

  g_mean <-  a$statistics[grep("g\\[", rownames(a$statistics)), "Mean"]
  treat_mean <- a$statistics[grep("d\\[", rownames(a$statistics)), "Mean"]
  treat_mean <- treat_mean["d[2]"]
  names(treat_mean) <- "treat"
  mean_values <- c(g_mean, treat_mean)
  bayesLASSO_store_mse[i,] <- find_performance(mean_values, correct_em_values, correct_em)

  g_sd <-  a$statistics[grep("g\\[", rownames(a$statistics)), "SD"]
  treat_sd <- a$statistics[grep("d\\[", rownames(a$statistics)), "SD"]
  treat_sd <- treat_sd["d[2]"]
  names(treat_sd) <- "treat"
  sd_values <- c(g_sd, treat_sd)
  bayesLASSO_store_sd[i,] <- find_performance2(sd_values, correct_em)
}
bayesLASSO_store_mse_mean <- apply(bayesLASSO_store_mse, 2, mean)
bayesLASSO_store_sd_mean <- apply(bayesLASSO_store_sd, 2, mean)
```


## SSVS

```{r SSVS_store, cache = TRUE, results = "hide"}
SSVS_store_mse <- matrix(NA, nrow = niter, ncol = 3)
SSVS_store_sd <- matrix(NA, nrow = niter, ncol = 2)

for(i in seq(niter)){

  set.seed(i)
  data <-generate.simulation(Nstudies = 5, Ncovariate = 5, continuous.cov = c(1, 3, 4), pf = c(1,2,3), em = 3, b1 = c(0.1, 0.5, 0.1), b2 = 0.1)
  data_jags <- with(data,{
                  list(Nstudies = length(unique(studyid)),
                  X = cbind(X1, X2, X3, X4, X5),
                  Np = length(X1),
                  Ncovariate = (dim(data)[2] - 3)/2,
                  studyid = studyid,
                  treat = treat + 1,
                  y = y)
  })
  
  samples <- jags.parfit(cl = cl, data = data_jags, params = c("g", "d"), model = "IPD-MA-SSVS.txt", n.chains = 3, n.adapt = 100, n.update = 100, n.iter = 2000)
  
  a <- summary(samples)

  g_mean <-  a$statistics[grep("g\\[", rownames(a$statistics)), "Mean"]
  treat_mean <- a$statistics[grep("d\\[", rownames(a$statistics)), "Mean"]
  treat_mean <- treat_mean["d[2]"]
  names(treat_mean) <- "treat"
  mean_values <- c(g_mean, treat_mean)
  SSVS_store_mse[i,] <- find_performance(mean_values, correct_em_values, correct_em)
  
  g_sd <-  a$statistics[grep("g\\[", rownames(a$statistics)), "SD"]
  treat_sd <- a$statistics[grep("d\\[", rownames(a$statistics)), "SD"]
  treat_sd <- treat_sd["d[2]"]
  names(treat_sd) <- "treat"
  sd_values <- c(g_sd, treat_sd)
  SSVS_store_sd[i,] <- find_performance2(sd_values, correct_em)
}
SSVS_store_mse_mean <- apply(SSVS_store_mse, 2, mean)
SSVS_store_sd_mean <- apply(SSVS_store_mse, 2, mean)
```



```{r}
result_matrix_mse <- matrix(NA, nrow = 7, ncol = 3)
colnames(result_matrix_mse) <- c("false em mse", "true em mse","treatment mse")
rownames(result_matrix_mse) <-  c("simple null", "simple lm","naive step", "naive lasso", "glmmLasso", "bayes lasso", "SSVS")
result_matrix_mse[1,] <- glmm_null_store_mse_mean
result_matrix_mse[2,] <- glmm_full_store_mse_mean
result_matrix_mse[3,] <- step_store_mse_mean
result_matrix_mse[4,] <- glmnet_store_mse_mean
result_matrix_mse[5,] <- glmmLasso_store_mse_mean
result_matrix_mse[6,] <- bayesLASSO_store_mse_mean
result_matrix_mse[7,] <- SSVS_store_mse_mean
kable(result_matrix_mse)

result_matrix_sd <- matrix(NA, nrow = 7, ncol = 2)
colnames(result_matrix_sd) <- c("average effect modifier se","treatment se")
rownames(result_matrix_sd) <-  c("simple null", "simple lm","naive step", "naive lasso", "glmmLasso", "bayes lasso", "SSVS")
result_matrix_sd[1,] <- glmm_null_store_sd_mean
result_matrix_sd[2,] <- glmm_full_store_sd_mean
result_matrix_sd[3,] <- step_store_sd_mean
#result_matrix_sd[4,] <- glmnet_store_sd_mean
#result_matrix_sd[5,] <- glmmLasso_store_sd_mean
result_matrix_sd[6,] <- bayesLASSO_store_sd_mean
#result_matrix_sd[7,] <- SSVS_store_sd_mean
kable(result_matrix_sd)
```
