---
title: "Simulations"
author: "Michael Seo"
date: "16 August 2019"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE, tidy.opts=list(blank=FALSE, width.cutoff=60), warning = FALSE, message=FALSE, echo = FALSE)
```


```{r}
# load packages needed
library(MASS) # Used for data simulation

library(lme4) #for fitting glmm
library(glmnet) #for lasso
library(dclone) # for parallel processing of JAGS code

library(writexl)

setwd("C:/Users/mike/Desktop/Github/phd/shrinkage/simulation")
#setwd("~/GitHub/phd/shrinkage/simulation")

source("run.simulation.functions.final.R")
source("helpful.functions.final.R")

# setup for parallel computing
n.cores <- 2
cl <- makePSOCKcluster(n.cores)
tmp <- clusterEvalQ(cl, library(dclone))

# number of simulation to run
niter <- 1000

start_time <- Sys.time()
```

## Simulation

```{r, simulation}
### parameters to change ###
col_labels <- c(paste0("X", 1:30, ":treat"), "treat")

correct_em <- c(rep(0, 14), 1, rep(0, 15))
correct_em_values <- c(rep(0, 14), 0.5, rep(0, 15))

Nstudies <- 5
Ncovariate <- 30
continuous.cov <- c(1:7, 15, 16:23)
pf <- 1:15
em <- 15
beta <- rep(0.2, 15)
gamma <- 0.5
tau <- 0.5

glmm_oracle_formula <- as.formula("y ~ studyid + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 + X14 + X15 + X15:treat + treat + (-1 + treat|studyid)")
glmm_full_formula <- as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 + X14 + X15 + X16 + X17 + X18 + X19 + X20 + X21 + X22 + X23 + X24 + X25 + X26 + X27 + X28 + X29 + X30)*treat + (-1 + treat|studyid)")
step_full_formula <-  as.formula("y ~ studyid + (X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 + X14 + X15 + X16 + X17 + X18 + X19 + X20 + X21 + X22 + X23 + X24 + X25 + X26 + X27 + X28 + X29 + X30)*treat")
step_lower_formula <- as.formula(" ~ studyid + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 + X14 + X15 + X16 + X17 + X18 + X19 + X20 + X21 + X22 + X23 + X24 + X25 + X26 + X27 + X28 + X29 + X30 + treat")

model.type = "gaussian"
t_dist = FALSE
sampleSize = c(50, 100)
```

```{r simulationa, cache = TRUE, result = "hide", include = FALSE}
simulation.a <- run.simulation()
```

```{r simulationb, cache = TRUE, result = "hide", include = FALSE}
simulation.b <- run.simulation2()
```

```{r simulationc, cache = TRUE, result = "hide", include = FALSE}
simulation.c <- run.simulation3()
```

```{r simulationb2, cache = TRUE, result = "hide", include = FALSE}
simulation.b2 <- run.simulation2.1()
```

```{r}
simulation.a
simulation.b
simulation.c
simulation.b2
#write_xlsx(as.data.frame(round(simulation.result,3)), "simulation5.xlsx")
```

```{r}
end_time <- Sys.time()
end_time - start_time
```